[package]
name = "nxray"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "nx"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pest = "2.7"
pest_derive = "2.7"
pnet = "0.35"
